Add iCubErzelli02
robotology/icub-models-generator pull request #195
Opened 2021-02-16 12:15 UTC by Nicogene

This PR adds the robot `iCubErzelli02`

Please review code.

2021-02-16 13:04 UTC, traversaro commented
According to https://icub-tech-iit.github.io/documentation/icub_versions/, iCub 2.5 with backpack is 2.5.5, but in https://robot-bazaar.iit.it/'s robot manager iCubErzelli02 is listed as 2.5 (not 2.5.5), as I guess you verified on the real robot, perhaps we can open an issue in https://github.com/icub-tech-iit/appsAway to ensure that the robot manager entry for iCubErzelli02 is correctly updated? Thanks! 

fyi @vtikha @Fabrizio69

2021-02-16 13:06 UTC, traversaro commented on README.md
> +| `iCubErzelli02`      | simmechanics | v2.5   with backpack            |
```suggestion
| `iCubErzelli02`      | simmechanics | v2.5.5         |
```

The correct version identified for v2.5 with backpack is v2.5.5, see https://icub-tech-iit.github.io/documentation/icub_versions/ . The other entries are outdated and probably could be updated in another issue.

2021-02-16 13:07 UTC, traversaro requested changes
Minor comments.

2021-02-16 13:49 UTC, Nicogene commented
It has for sure the backpack but not the battery as far as I know, also without the battery is 2.5.5?

2021-02-16 13:58 UTC, traversaro commented
> 
> 
> It has for sure the backpack but not the battery as far as I know, also without the battery is 2.5.5?

I think so. However, if this is not clear from https://icub-tech-iit.github.io/documentation/icub_versions/ we should open an issue in https://github.com/icub-tech-iit/documentation

2021-02-16 13:59 UTC, traversaro commented
Note that if there is the backpack, but there is no dummy weight that simulate the presence of the battery, then the difference in weight may affect the torque estimation or any other use of the URDF model that uses inertial information of the `chest` link.

2021-02-22 10:45 UTC, traversaro commented
If you prefer we can merge as it is and open issues for tracking the doubts on configuration versions @Nicogene .

2021-02-22 11:52 UTC, merged

2021-02-22 11:53 UTC, Nicogene commented
Ok I will try  the wbd device  with the urdf generated and we will see what happens

2021-02-22 11:59 UTC, traversaro commented
Ok, please remember to open issues otherwise it is quite easy to forget about this tricky aspects.

2021-03-30 07:42 UTC, traversaro commented
> Ok, please remember to open issues otherwise it is quite easy to forget about this tricky aspects.

Hi @Nicogene, just to understand did we opened the issue on the fake iCubErzelli02 backpack?

2021-03-30 08:16 UTC, Nicogene commented
Yes here it is #196

2021-03-30 08:28 UTC, traversaro commented
> 
> 
> Yes here it is #196

Thanks! For the future let's remember to cross-link related issues so we can find them later.