Update xsens root_link imu configuration file in order to publish correctly with iCubGazeboV2_7
robotology/icub-models-generator pull request #246
Opened 2023-08-31 10:08 UTC by martinaxgloria

This PR fixes https://github.com/robotology/icub-models-generator/issues/245

The updates introduced with https://github.com/robotology/icub-models-generator/pull/231 don't affect the xsens on the root link. This causes errors when iCubGazeboV2_7 model is loaded on gazebo:

```
[ERROR] |yarp.os.YarpPluginSettings| Cannot find "inertial" plugin (not built in, and no .ini file found for it)Check that YARP_DATA_DIRS leads to at least one directory with plugins/inertial.ini or share/yarp/plugins/inertial.ini in it
[ERROR] |yarp.dev.PolyDriver|inertial| Could not find device <inertial>
[ERROR] GazeboYarpIMU Plugin Load failed: error in opening yarp driver
```

2023-08-31 10:15 UTC, traversaro commented
Thanks @martinaxgloria ! Are you sure that this PR fixes https://github.com/robotology/icub-models-generator/issues/245 ? In particular, it is not clear to me how the measure of the IMU is published for the xsens root_link IMU in this case.

2023-08-31 11:57 UTC, martinaxgloria commented
Sorry @traversaro, I mean that with these changes the errors mentioned above disappear. I attach here the log:

- [iCub_V2_7.log](https://github.com/robotology/icub-models-generator/files/12485153/icub_V2_7.log)

2023-08-31 14:44 UTC, traversaro requested changes
See https://github.com/robotology/icub-models-generator/pull/246/commits/ef49e1959c6653b57c61c9823d6c5475aa394f8c#r1311744863 .

2023-08-31 14:50 UTC, Nicogene commented on simmechanics/data/icub2_5/conf/icub.xml
> +    <xi:include href="wrappers/inertials/waist-inertials_wrapper.xml" />
Yes, nice catch I didn't notice it

2023-08-31 15:08 UTC, martinaxgloria commented on simmechanics/data/icub2_5/conf/icub.xml
> +    <xi:include href="wrappers/inertials/waist-inertials_wrapper.xml" />
Yes, you're right. I will restore it

2023-09-01 09:07 UTC, Nicogene approved these changes
Until we can use the `subdevice` clause I think it is a good compromise

2023-09-01 10:40 UTC, traversaro commented
Did you try if this is actually working? I am afraid we are hardcoding inertial in gazebo-yarp-plugins .

2023-09-01 10:46 UTC, traversaro commented
> Did you try if this is actually working? I am afraid we are hardcoding inertial in gazebo-yarp-plugins .

Actually, we should be good to go : https://github.com/robotology/gazebo-yarp-plugins/blob/0fd9300b583267c7bff4fb2be7fe82700ddeb613/plugins/imu/src/IMU.cc#L98 .

2023-09-01 11:44 UTC, Nicogene commented
> > Did you try if this is actually working? I am afraid we are hardcoding inertial in gazebo-yarp-plugins .
> 
> Actually, we should be good to go : [robotology/gazebo-yarp-plugins@`0fd9300`/plugins/imu/src/IMU.cc#L98](https://github.com/robotology/gazebo-yarp-plugins/blob/0fd9300b583267c7bff4fb2be7fe82700ddeb613/plugins/imu/src/IMU.cc#L98) , but perhaps we should put this in the `WRAPPER` group?

Maybe we need to set `disableImplicitWrapper`?

2023-09-01 11:47 UTC, martinaxgloria commented
> Actually, we should be good to go : https://github.com/robotology/gazebo-yarp-plugins/blob/0fd9300b583267c7bff4fb2be7fe82700ddeb613/plugins/imu/src/IMU.cc#L98 , but perhaps we should put this in the `WRAPPER` group?

Actually, this warning message is printed out but it doesn't cause the yarprobotinterface to close. I attach here the log:

[iCubGazeboV2_7.log](https://github.com/robotology/icub-models-generator/files/12497514/iCubGazeboV2_7.log)

And xsens data were published correctly on the port.

2023-09-01 11:51 UTC, traversaro commented
Perfect!

2023-09-01 11:51 UTC, traversaro approved these changes

2023-09-01 11:52 UTC, merged

2023-09-01 11:53 UTC, traversaro commented
I opened https://github.com/robotology/icub-models-generator/issues/247 to track a proper solution.